### ISSUE TITLE
options.ts中生成的model路径在windows下会被转义

### ISSUE THREAD

**Issue by jimlaren** [duan602728596/umi-plugin-redux-toolkit#1]
生成的options.ts文件中，import model的路径应该生成为
import model_login_0 from 'x:/src/models/login.ts';
目前生成为：import model_login_0 from 'x:\src\models\login.ts';
这个路径会被转义并识别为一个ts文件，报错：This dependency was not found

**Comment by duan602728596** [comment]
应该是window下获取的路径问题，我处理一下

**Comment by duan602728596** [comment]
已发版

**Comment by jimlaren** [comment]
可以了，测试中，万分感谢。

**Comment by duan602728596** [comment]
那就ok了
